wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704891227.574053
    t:
      1:
      - 1
      - 55
      - 100
      2:
      - 1
      - 11
      - 49
      - 55
      - 100
      3:
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.0001
val_percent:
  desc: null
  value: 0.3
save_checkpoint:
  desc: null
  value: true
img_scale:
  desc: null
  value: 0.5
amp:
  desc: null
  value: true
